#!/bin/env bash

ENDPOINT_FILE="$HOME/vpn/test_endpoint"

vpn() {
  if [ -f "${ENDPOINT_FILE}" ]; then
    if ping $(cat "${ENDPOINT_FILE}") -c 1 > /dev/null 2>&1; then
      icon=""
      class=on
    else
      icon=""
      class=off
    fi
    printf '{"text": " %s ", "class": "%s"}\n' "$icon" "$class"
  fi
}

while true; do
  vpn
  sleep 30s
done
