---
default_xdg_config_home: "{{ ansible_user_dir }}/.config"
default_xdg_data_home: "{{ ansible_user_dir }}/.local/share"
default_xdg_cache_home: "{{ ansible_user_dir }}/.cache"

# http://standards.freedesktop.org/basedir-spec/basedir-spec-latest.html
# default: $XDG_CONFIG_HOME | ~/.config/
xdg_config_home: "{{ ansible_env.XDG_CONFIG_HOME | default(default_xdg_config_home) }}"
# default: $XDG_DATA_HOME | ~/.local/share/
xdg_data_home: "{{ ansible_env.XDG_DATA_HOME | default(default_xdg_data_home) }}"
# default: $XDG_CACHE_HOME | ~/.cache
xdg_cache_home: "{{ ansible_env.XDG_CACHE_HOME | default(default_xdg_cache_home) }}"
