# TokyoNight Alacritty Colors
colors:
  # Default colors
  primary:
    background: "0x24283b"
    foreground: "0xc0caf5"

  # Normal colors
  normal:
    black: "0x9394a9"
    red: "0xf7768e"
    green: "0x73daca"
    yellow: "0xe0af68"
    blue: "0x7aa2f7"
    magenta: "0xbb9af7"
    cyan: "0x7dcfff"
    white: "0xa8b1d6"

  # Bright colors
  bright:
    black: "0x9195a8"
    red: "0xf7768e"
    green: "0x73daca"
    yellow: "0xe0af68"
    blue: "0x7aa2f7"
    magenta: "0xbb9af7"
    cyan: "0x7dcfff"
    white: "0xa8b1d6"

  indexed_colors:
    - { index: 16, color: "0xff9e64" }
    - { index: 17, color: "0xdb4b4b" }
