---
- name: Allow sudo with TouchID
  become: true
  pamd:
    name: sudo
    type: auth
    control: sufficient
    module_path: pam_smartcard.so
    new_type: auth
    new_control: sufficient
    new_module_path: pam_tid.so
    state: before

- name: "determine user id"
  ansible.builtin.set_fact:
    ansible_user_uid: "{{ lookup('pipe', 'id -u ' + ansible_user_uid | quote ) }}"

- name: Manage XDG_RUNTIME_DIR
  become: true
  ansible.builtin.file:
    path: "/run/user/{{ ansible_user_uid }}"
    state: directory
    mode: '0700'
    owner: "{{ ansible_user_uid }}"
