# espanso match file
# For a complete introduction, visit the official docs at: https://espanso.org/docs/

matches:
  # Print the current date
  - trigger: ":date"
    replace: "{{mydate}}"
    vars:
      - name: mydate
        type: date
        params:
          format: "%m/%d/%Y"

  - trigger: "mvg,"
    replace: |
      Met vriendelijke groet,
      Bernd Schörgers
