---
- name: "install nvim"
  community.general.homebrew:
    name:
      - nvim
  tags: homebrew

- name: Check lunarvim install location
  ansible.builtin.stat:
    path: "{{ xdg_data_home }}/lunarvim"
  register: lunarvim_install_location

- name: "create config dir"
  ansible.builtin.file:
    path: "{{ xdg_config_home }}/lvim"
    state: directory
    mode: '0755'

- name: "download"
  ansible.builtin.get_url:
    url: https://raw.githubusercontent.com/lunarvim/lunarvim/rolling/utils/installer/install.sh
    dest: /tmp/install-lunarvim.sh
    mode: '0755'
  register: download_result
  until: download_result is succeeded
  retries: 3
  delay: 5
  when:
    - not lunarvim_install_location.stat.exists

- name: "install"
  ansible.builtin.command: /tmp/install-lunarvim.sh --no-install-dependencies --yes
  when:
    - not lunarvim_install_location.stat.exists
