---
- name: "determine user font folder"
  ansible.builtin.set_fact:
    user_font_folder: |-
      {%- if ansible_system == "Darwin" -%}
        {{ ansible_user_dir }}/Library/Fonts
      {%- elif ansible_system == "Linux" -%}
        {{ xdg_data_home }}/fonts
      {%- endif -%}

- name: "install firacode font"
  include_tasks: install_font.yaml
  vars:
    install_path: "{{ user_font_folder }}"
    font_name: firacode_nerd_font
    version: 2.2.2
    url: https://github.com/ryanoasis/nerd-fonts/releases/download/v{{version}}/FiraCode.zip
    font_format: archive
