palette = "catppuccin_macchiato"

format = """\
[\uE0B6](fg:blue bg:background)$time\
[\uE0B0](fg:blue bg:green)$kubernetes\
[\uE0B0](fg:green bg:yellow)$git_branch\
[\uE0B0](fg:yellow bg:flamingo)$python$terraform$golang\
[\uE0B0](fg:flamingo bg:background)
$directory\
$character
"""

[time]
disabled = false
time_format = "%R" # Hour:Minute Format
style = "bg:blue"
format = '[[ 󱑍 $time ](bg:blue fg:surface0)]($style)'

[directory]
format = "[   $path]($style)"
style = "fg:lavender"
truncation_length = 4
truncation_symbol = "…/"

[git_branch]
format = '[ $symbol$branch(:$remote_branch) ]($style)'
symbol = "  "
style = " bg:yellow fg:#1C3A5E"

[character]
success_symbol = '[ >](bold green)'
error_symbol = '[ ✗](#E84D44)'

[kubernetes]
symbol = "󱃾 "
format = "[ $symbol$context \\($namespace\\) ]($style)"
style  = "bg:green fg:surface1"
disabled = false

[python]
symbol = " "
format = "[ $symbol$pyenv_prefix($version )(\\($virtualenv\\)) ]($style)"
style  = "bg:flamingo fg:surface0"

[golang]
symbol = " "
format = "[ $symbol($version) ]($style)"
style = " bg:flamingo fg:surface0"

[terraform]
symbol = "󱁢 "
format = "[ $symbol$version ]($style)"
style = "bg:flamingo fg:surface0"

[palettes.catppuccin_macchiato]
background = "#24273a"
rosewater = "#f4dbd6"
flamingo = "#f0c6c6"
pink = "#f5bde6"
mauve = "#c6a0f6"
red = "#ed8796"
maroon = "#ee99a0"
peach = "#f5a97f"
yellow = "#eed49f"
green = "#a6da95"
teal = "#8bd5ca"
sky = "#91d7e3"
sapphire = "#7dc4e4"
blue = "#8aadf4"
lavender = "#b7bdf8"
text = "#cad3f5"
subtext1 = "#b8c0e0"
subtext0 = "#a5adcb"
overlay2 = "#939ab7"
overlay1 = "#8087a2"
overlay0 = "#6e738d"
surface2 = "#5b6078"
surface1 = "#494d64"
surface0 = "#363a4f"
base = "#24273a"
mantle = "#1e2030"
crust = "#181926"
